name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run tests
      run: npm test
      working-directory: ./backend

    - name: Login to Heroku
      run: echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token

    - name: Set up Heroku remote
      run: heroku git:remote -a hng-social-network

    - name: Initialize Git (if not already initialized)
      run: |
        git init
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy to Heroku" || echo "No changes to commit"

    - name: Deploy to Heroku
      run: git push heroku main
